# This is the name shown in the GitHub Actions tab
name: Build C# Project

# This controls when the workflow runs
on:
  push:
    # Run only when code is pushed to the master/main branch
    branches:
      - master
      - main

  # This allows you to manually run the workflow from GitHub
  workflow_dispatch:

# Give the workflow read-only access to the repository contents
permissions:
  contents: read

jobs:
  build:
    # Name of the job shown in GitHub Actions
    name: Build

    # Use a Linux machine provided by GitHub
    runs-on: ubuntu-latest

    steps:
      # Download the repository code into the workflow machine
      - name: Get code from repository
        uses: actions/checkout@v7

      # Install the .NET SDK
      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          # Change this if your project uses a different .NET version
          dotnet-version: '10.0.x'

      # Restore NuGet packages
      # - name: Restore dependencies
      #   run: dotnet restore

      # Build the project in Release mode
      # - name: Build project
      #   run: dotnet build --configuration Release --no-restore

      # Restoring Week 1 Project 
      - name: Restore Week 1 Project 
        run: dotnet restore ./Week_1/FirstConsoleApp/FirstConsoleApp.csproj

      #Building Week 1 Project
      - name: Build Week 1 Project 
        run: dotnet build ./Week_1/FirstConsoleApp/FirstConsoleApp.csproj --configuration Release --no-restore
        
      # Restoring Week 1 Review Project 
      - name: Restore Week 1 Review Project 
        run: dotnet restore ./Week_1_Review/ReviewConsoleApp/ReviewConsoleApp.csproj

      #Building Week 1 Project
      - name: Build Week 1 Project 
        run: dotnet build ./Week_1_Review/ReviewConsoleApp/ReviewConsoleApp.csproj --configuration Release --no-restore

      # Restoring Week 2 Project 
      - name: Restore Week 2 Project 
        run: dotnet restore ./Week_2/BasicProgrammingApp/BasicProgrammingApp.csproj

      #Building Week 2 Project
      - name: Build Week 2 Project 
        run: dotnet build ./Week_2/BasicProgrammingApp/BasicProgrammingApp.csproj --configuration Release --no-restore

      # Restoring Week 3 Project 
      - name: Restore Week 3 Project 
        run: dotnet restore ./Week_3/ClassesAndObjectsApp/ClassesAndObjectsApp.csproj

      #Building Week 3 Project
      - name: Build Week 3 Project 
        run: dotnet build ./Week_3/ClassesAndObjectsApp/ClassesAndObjectsApp.csproj --configuration Release --no-restore


      # Restoring Week 5 Project 
      - name: Restore Week 5 Project 
        run: dotnet restore ./Week_5/TaskManagerApi/TaskManagerApi.csproj

      #Building Week 5 Project
      - name: Build Week 5 Project 
        run: dotnet build ./Week_5/TaskManagerApi/TaskManagerApi.csproj --configuration Release --no-restore


      # Restoring Week 6 Project 
      - name: Restore Week 6 Project 
        run: dotnet restore ./Week_6/TaskManagerApi/TaskManagerApi.csproj

      #Building Week 6 Project
      - name: Build Week 6 Project 
        run: dotnet build ./Week_6/TaskManagerApi/TaskManagerApi.csproj --configuration Release --no-restore

      # Restoring Week 7 Project
      - name: Restore Week 7 Project
        run: dotnet restore ./Week_7/TaskManagerApi/TaskManagerApi.csproj

      #Building Week 7 Project
      - name: Build Week 7 Project
        run: dotnet build ./Week_7/TaskManagerApi/TaskManagerApi.csproj --configuration Release --no-restore
